# Generated by Django 3.2.3 on 2021-10-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=700)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rate'],
            },
        ),
    ]
